src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\PasswordHasher\Hasher\PasswordHasherAwareInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

/**
 * Utilisateur
 *
 * @ORM\Table(name="utilisateur", indexes={@ORM\Index(name="utilisateur_lieu_FK", columns={"id_lieu"}), @ORM\Index(name="utilisateur_role0_FK", columns={"id_role"})})
 * @ORM\Entity(repositoryClass= "App\Repository\UtilisateurRepository")
 */

#[UniqueEntity(
    fields: ['loginUtilisateur'],
    errorPath: 'loginUtilisateur',
    message: 'Cet email semble déjà être utilisé, veuillez en choisir une autre.'
    )]

class Utilisateur implements UserInterface, PasswordAuthenticatedUserInterface, PasswordHasherAwareInterface
{
    /**
     * @var int
     *
     * @ORM\Column(name="id_utilisateur", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $idUtilisateur;

    /**
     * @var string
     *
     * @ORM\Column(name="nom_utilisateur", type="string", length=50, nullable=false)
     */
    private $nomUtilisateur;

    /**
     * @var string
     *
     * @ORM\Column(name="prenom_utilisateur", type="string", length=50, nullable=false)
     */
    private $prenomUtilisateur;

    /**
     * @var string
     *
     * @ORM\Column(name="pseudo_utilisateur", type="string", length=250, nullable=false)
     */
    private $pseudoUtilisateur;

    /**
     * @var string
     *
     * @ORM\Column(name="login_utilisateur", type="string", length=100, nullable=false)
     * @Assert\Email()
     */
    private $loginUtilisateur;

    /**
     * @var string
     *
     * @ORM\Column(name="mdp_utilisateur", type="string", length=500, nullable=false)
     */
    #[Assert\Length(
        min: 8,
        max: 14,
        minMessage: 'mot de passe trop court',
        maxMessage:'mot de passe trop long ',
    )]
    private $mdpUtilisateur;

    /**
     * @var string
     *
     * @ORM\Column(name="adressse", type="string", length=250, nullable=false)
     */
    private $adressse;

    /**
     * @var float
     *
     * @ORM\Column(name="longitude_adresse", type="float", precision=10, scale=0, nullable=false)
     */
    private $longitudeAdresse;

    /**
     * @var float
     *
     * @ORM\Column(name="latitude_adresse", type="float", precision=10, scale=0, nullable=false)
     */
    private $latitudeAdresse;

    /**
     * @var bool
     *
     * @ORM\Column(name="is_verified", type="boolean", nullable=false)
     */
    private $is_verified = false;

    /**
     * @var \Role
     *
     * @ORM\ManyToOne(targetEntity="Role")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_role", referencedColumnName="id_role")
     * })
     */
    private $idRole;

    /**
     * @var \Lieu
     *
     * @ORM\ManyToOne(targetEntity="Lieu")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_lieu", referencedColumnName="id_lieu")
     * })
     */
    private $idLieu;



    public function getIdUtilisateur(): ?int
    {
        return $this->idUtilisateur;
    }

    public function getNomUtilisateur(): ?string
    {
        return $this->nomUtilisateur;
    }

    public function setNomUtilisateur(string $nomUtilisateur): self
    {
        $this->nomUtilisateur = $nomUtilisateur;

        return $this;
    }

    public function getPrenomUtilisateur(): ?string
    {
        return $this->prenomUtilisateur;
    }

    public function setPrenomUtilisateur(string $prenomUtilisateur): self
    {
        $this->prenomUtilisateur = $prenomUtilisateur;

        return $this;
    }

    public function getPseudoUtilisateur(): ?string
    {
        return $this->pseudoUtilisateur;
    }

    public function setPseudoUtilisateur(string $pseudoUtilisateur): self
    {
        $this->pseudoUtilisateur = $pseudoUtilisateur;

        return $this;
    }

    public function getLoginUtilisateur(): ?string
    {
        return $this->loginUtilisateur;
    }

    public function setLoginUtilisateur(string $loginUtilisateur): self
    {
        $this->loginUtilisateur = $loginUtilisateur;

        return $this;
    }

    public function getMdpUtilisateur(): ?string
    {
        return $this->mdpUtilisateur;
    }

    public function setMdpUtilisateur(string $mdpUtilisateur): self
    {
        $this->mdpUtilisateur = $mdpUtilisateur;

        return $this;
    }

    public function getAdressse(): ?string
    {
        return $this->adressse;
    }

    public function setAdressse(string $adressse): self
    {
        $this->adressse = $adressse;

        return $this;
    }

    public function getLongitudeAdresse(): ?float
    {
        return $this->longitudeAdresse;
    }

    public function setLongitudeAdresse(float $longitudeAdresse): self
    {
        $this->longitudeAdresse = $longitudeAdresse;

        return $this;
    }

    public function getLatitudeAdresse(): ?float
    {
        return $this->latitudeAdresse;
    }

    public function setLatitudeAdresse(float $latitudeAdresse): self
    {
        $this->latitudeAdresse = $latitudeAdresse;

        return $this;
    }

    public function getIsVerified(): ?bool
    {
        return $this->is_verified;
    }

    public function setIsVerified(bool $is_verified): self
    {
        $this->is_verified = $is_verified;

        return $this;
    }


    public function getIdRole(): ?Role
    {
        return $this->idRole;
    }

    public function setIdRole(?Role $idRole): self
    {
        $this->idRole = $idRole;

        return $this;
    }

    public function getIdLieu(): ?Lieu
    {
        return $this->idLieu;
    }

    public function setIdLieu(?Lieu $idLieu): self
    {
        $this->idLieu = $idLieu;

        return $this;
    }

       //--------- UserInterface

    /**
     * The public representation of the user (e.g. a username, an email address, etc.)
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->loginUtilisateur;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {        
        $roles[] = 'ROLE_USER';
        return array_unique($roles);
    }

    /**
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
    }

    /**
      * @see PasswordAuthenticatedUserInterface
      */

    public function getPassword(): string

    {
        return $this->mdpUtilisateur;
    }

    public function getPasswordHasherName(): ?string

    {
        return null;
    }

}

src/Controller/DashboardController.php
<?php

namespace App\Controller;

use DateTime;
use App\Entity\Image;
use App\Entity\Animal;
use App\Form\AnnonceType;
use Doctrine\ORM\EntityManager;
use App\Repository\ImageRepository;
use App\Repository\AnimalRepository;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\UtilisateurRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class DashboardController extends AbstractController
 {
    #[ Route( '/dashboard', name: 'app_dashboard' ) ]

    public function index(EntityManagerInterface $manager, UtilisateurRepository $repoUtilisateur, ImageRepository $imageRepo, AnimalRepository $repoAnimal, UserInterface $utilisateurCo ): Response
 {
        
        $animals = $repoAnimal->articleParSonIdUtilisateur($utilisateurCo);
        $utilisateur = $repoUtilisateur->findOneByIdUtilisateur($utilisateurCo);
        $manager->persist($utilisateur);
        return $this->render( 'dashboard/index.html.twig', [
            'animals' => $animals,
            'utilisateur'=>$utilisateur,
        ] );
    }

    #[ Route( 'dashboard/delete/{id}', methods: [ 'GET' ], name:'delete_annonce' ) ]

    public function delete( $id,  AnimalRepository $animalRepository,  ImageRepository $imageRepository, EntityManagerInterface $em ): Response
 {
        $images = $imageRepository->findByIdAnimal($id);
        foreach ($images as $image) {
            $em->remove($image);
            $em->flush();
        }
        $animals = $animalRepository->findOneByIdAnimal($id);
        $em->remove($animals);
        $em->flush();

        return $this->redirectToRoute('app_dashboard');
    }

    #[ Route( '/dashboard/ajouter-article', name: 'app_dashboard_ajouter' ) ]

    public function ajouterAnnoce( Request $request, UserInterface $utilisateurCo, EntityManagerInterface $manager, AnimalRepository $repoAnimal ): Response {

        $animal = new Animal();
        $form_animal = $this->createForm( AnnonceType::class, $animal );
        $form_animal->handleRequest( $request );
        if ( $form_animal->isSubmitted() && $form_animal->isValid() ) {
            $animal->setIdUtilisateur( $utilisateurCo );
            $manager->persist( $animal );
            $manager->flush();
            $images =  $form_animal->get( 'images' )->getData();
            foreach ( $images as $image ) {
                $fichier = md5( uniqid() ).'.'.$image->guessExtension();
                $image->move(
                    $this->getParameter( 'images_directory' ),
                    $fichier
                );
                $img = new Image();
                $img->setImage( $fichier );
                $img->setIdAnimal( $animal );
                $manager->persist( $img );
            }
            $manager->flush();
            $this->addFlash( 'success', "<script>Swal.fire({
                position: 'center',
                icon:'success', 
                title:'Votre annonce a bien ete ajouté !', 
                showCinfirmation:false,
                timer: 1500
            })</script>" );
            return $this->redirectToRoute( 'app_dashboard_ajouter' );
        }
        return $this->render( 'dashboard/ajouter.html.twig', [
            'controller_name' => 'AjouterArticleController',
            'form_animal' => $form_animal->createView(),
        ] );
    }
}

templates/dashboard/ajouter.html.twig
{% extends 'base.html.twig' %}
{% block title %}Hello DashboardController!
{% endblock %}
{% block stylesheets %}
	<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
	<script src="https://cdn.jsdelivr.net/npm/zangdar@1.0.25/dist/zangdar.min.js"></script>
	<link href="{{asset('css/dashboard.css')}}" rel="stylesheet">
{% endblock %}
{% block body %}
	<style>
		body {
			background-color: #f5f5f5;
		}
		.imagePreview {
			width: 100%;
			height: 180px;
			background-position: center center;
			background: url('http://cliquecities.com/assets/no-image-e3699ae23f866f6cbdf8ba2443ee5c4e.jpg');
			background-color: #fff;
			background-size: cover;
			background-repeat: no-repeat;
			display: inline-block;
			box-shadow: 0 -3px 6px 2px rgba(0, 0, 0, 0.2);
		}
		.btn-primary {
			display: block;
			border-radius: 0;
			box-shadow: 0 4px 6px 2px rgba(0, 0, 0, 0.2);
			margin-top: -5px;
			height: 50px;
		}
		.imgUp {
			margin-bottom: 15px;
		}
		.del {
			z-index: 5;
			position: relative;
			top: -88%;
			right: -87%;
			width: 30px;
			height: 30px;
			text-align: center;
			line-height: 30px;
			background-color: rgba(255, 255, 255, 0.6);
			cursor: pointer;
		}
		.imgAdd {
			width: 30px;
			height: 30px;
			border-radius: 50%;
			background-color: #4bd7ef;
			color: #fff;
			box-shadow: 0 0 2px 1px rgba(0, 0, 0, 0.2);
			text-align: center;
			line-height: 30px;
			margin-top: 0;
			cursor: pointer;
			font-size: 15px;
		}

		.zandgar__wizard {
			display: block;
			height: 100%;
			position: relative;
		}

		.zandgar__wizard .zandgar__step {
			display: none;
		}
		.zandgar__wizard .zandgar__step.zandgar__step__active {
			display: block;
		}
	</style>

			{% include 'commun/nav.html.twig' %}
	<div class="container-fluid">
		<div class="row">
			<div class="container-fluid">
				<div class="row">
					<main class="col-md  px-md-4">
						<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
							<h1 class="h2">Créez une annonce
							</h1>
							<a class="nav-link " href="{{path('app_dashboard_ajouter')}}">
								<span data-feather="file" class="align-text-bottom"></span>
								Ajouter un article
							</a>
							<a class="nav-link active mx-2" aria-current="page" href="{{path('app_dashboard')}}">
								<span data-feather="home" class="align-text-bottom"></span>
								Mes annonces
							</a>
						</div>
					</main>
				</div>
			</div>

			<div class='row'>
				{% for message in app.flashes('success') %}
					<div class="flash-notice">
						{{ message | raw }}
					</div>
				{% endfor %}
			</div>
			<div class="container-fluid">
				<div class="row mx-auto">
					<div class=" col-lg-6 align-self-center mx-auto">
						<div class="m-3 m-lg-5">

							<div class="text-center mt-4 mb-3">
								<h1 class="h3">Créer une annonce</h1>
								<p class="lead">
									Veuillez entrer les information de l'animal à ajouter.
								</p>
							</div>

							<ul id="steps-native" class="nav nav-pills justify-content-center"></ul>

							{{form_start(form_animal,{'attr' : { 'class': 'my-2 py-2','id': 'wizard'   }})}}
							<section data-step="1. Account">
								<div class="row">
									<div class="col ">
										<div class="mb-3">
											<label class="form-label" for="nom">Nom de l'animal.</label>
											{{form_row(form_animal.nomAnimal)}}
										</div>
										<div class="mb-3">
											<label class="form-label" for="race">Choisissez la race.</label>
											{{form_row(form_animal.idRace)}}
										</div>
										<div id="statut" class="mb-3">
											<label class="form-label" for="statut">L'animal est il a vendre ou a donner ?</label>
											{{form_row(form_animal.idStatut)}}
										</div>
										<div id="prix" class="mb-3">
											<label class="form-label" for="prix">Entrez le prix de l'animal.</label>
											{{form_row(form_animal.prixAnimal)}}
										</div>
									</div>
									<div class="col">
										<div class="mb-3">
											<label class="form-label" for="LOF">Votre animal est il certifié LOF ?</label>
											{{form_row(form_animal.lofAnimal)}}
										</div>
										<div class="mb-3">
											<label class="form-label" for="sexe">Entrez le sexe de l'animal.</label>
											{{form_row(form_animal.isFeminin)}}
										</div>
										<div class="mb-3">
											<label class="form-label" for="sexe">l'animal est il vacciné ?</label>
											{{form_row(form_animal.isVaccine)}}
										</div>
										<div class="mb-3">
											<label class="form-label" for="sexe">L'animal est il identifié ?</label>
											{{form_row(form_animal.isIdentifie)}}
										</div>
									</div>
									<div class="row">
										<div class="col-12 text-right">
											<button class="btn btn-primary" data-next>Next</button>
										</div>
									</div>
								</div>
							</section>

							<section data-step="2. Profile">
								<div class="row">
									<div class="col">
										<div class="mb-3">
											<label class="form-label" for="first-name">Veuillez entrer la couleur de l'animal.</label>
											{{form_row(form_animal.idCouleur)}}
										</div>

										<div class="mb-3">
											<label class="form-label" for="last-name">Quel type de poil à l'animal ?</label>
											{{form_row(form_animal.idTypepoils)}}
										</div>
									</div>
									<div class="col">
										<div class="mb-3">
											<label class="form-label" for="last-name">Quel est la taille de l'animal ?</label>
											{{form_row(form_animal.idTaille)}}
										</div>

										<div class="mb-3">
											<label class="form-label" for="last-name">Quel est le poid de l'animal ?</label>
											{{form_row(form_animal.poidAnimal)}}
										</div>
									</div>
								</div>
								<div class="mb-3">
									<label class="form-label" for="last-name">Quel âge à l'animal ?</label>
									{{form_row(form_animal.ageAnimal)}}
								</div>

								<div class="mb-3">
									<label class="form-label" for="last-name">Veuillez entrer une description pour l'animal.</label>
									{{form_row(form_animal.texteAnimal)}}
								</div>

								<div class="row">
									<div class="col-6 text-left">
										<button class="btn btn-outline-primary" data-prev>Previous</button>
									</div>
									<div class="col-6 text-right">
										<button class="btn btn-primary" data-next>Next</button>
									</div>
								</div>
							</section>

							<section data-step="3. Social">
								<div class="row">
									<div class="col-sm-4 imgUp">
										<div class="imagePreview"></div>
										<label class="btn btn-primary">
											Upload{{form_row(form_animal.images)}}
										</label>
									</div>
									<!-- col-2 -->
									<i class="fa fa-plus imgAdd"></i>
								</div>
								<div class="row">
									<div class="col-6 text-left">
										<button class="btn btn-outline-primary" data-prev>Previous</button>
									</div>
									<div class="col-6 text-right">
										{{form_row(form_animal.save)}}
									</div>
								</div>
							</section>
							{{form_end(form_animal)}}
						</div>
					</div>
				</div>
			</div>

			{% for message in app.flashes('success') %}
				<div class="flash-notice"></div>

			</div>
		{% endfor %}


	</div>
	{% include 'commun/footer.html.twig' %}
</div>{% endblock %}{% block javascripts %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

{# pour faire le style du img upload #}
<script>
	let compteur = 0;

$(".imgAdd").click(function () {
$(this).closest(".row").find('.imgAdd').before('<div class="col-sm-4 imgUp"><div class="imagePreview"></div><label class="btn btn-primary">Upload<input type="file" name="annonce[images][]" class="uploadFile img" value="Upload Photo" style="width:0px;height:0px;overflow:hidden;"></label><i class="fa fa-times del"></i></div>');

compteur++;
console.log(compteur);
if (compteur >= 2) {
$(".imgAdd").removeClass("fa fa-plus imgAdd");

}
});
$(document).on("click", "i.del", function () {
compteur--;
$(this).parent().remove();

});
$(function () {
$(document).on("change", ".uploadFile", function () {
var uploadFile = $(this);
var files = !!this.files ? this.files : [];
if (! files.length || !window.FileReader) 
return;



// no file selected, or no FileReader support

if (/^image/.test(files[0].type)) { // only image file
var reader = new FileReader(); // instance of the FileReader
reader.readAsDataURL(files[0]); // read the local file

reader.onloadend = function () {
// set image data as background of div
// alert(uploadFile.closest(".upimage").find('.imagePreview').length);
uploadFile.closest(".imgUp").find('.imagePreview').css("background-image", "url(" + this.result + ")");
}
}

});
});
</script>

{# Pour faire le wizard form #}

<script>
	function buildStepsBreadcrumb(wizard, element, steps) {
const $steps = document.getElementById(element)
$steps.innerHTML = ''
for (let label in steps) {
if (steps.hasOwnProperty(label)) {
const $li = document.createElement('li')
const $a = document.createElement('a')
$li.classList.add('nav-item')
$a.classList.add('nav-link')
if (steps[label].active) {
$a.classList.add('active')
}
$a.setAttribute('href', '#')
$a.innerText = label
$a.addEventListener('click', e => {
e.preventDefault()
wizard.revealStep(label)
})
$li.appendChild($a)
$steps.appendChild($li)
}
}
}

function onStepChange(wizard, selector) {
const steps = wizard.getBreadcrumb()
buildStepsBreadcrumb(wizard, selector, steps)
}

const wizard = new window.Zangdar('#wizard', {
onStepChange: () => {
onStepChange(wizard, 'steps-native')
}

})

onStepChange(wizard, 'steps-native')
</script>


{# L'ajax pour faire apparaitre le prix #}
<script>
	$("#annonce_idStatut").change(function () {
if ($(this).val() == "2") {
$('#prix').show();
$('#annonce_prixAnimal').attr('required', '');
$('#annonce_prixAnimal').attr('data-error', 'This field is required.');
} else {
$('#prix').hide();
$('#annonce_prixAnimal').removeAttr('required');
$('#annonce_prixAnimal').removeAttr('data-error');
}
});
$("#annonce_idStatut").trigger("change");
</script>
<script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script>
<script src="{{asset('js/dashboard.js')}}"></script>{% endblock %}

templates/dashboard/index.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    <link href="{{asset('css/dashboard.css')}}" rel="stylesheet">
    {{ encore_entry_link_tags('app') }}
{% endblock %}

{% block title %}Coup de patte - Mon compte {% endblock %}

{% block body %}


	{% include 'commun/nav.html.twig' %}
<div class="container">
    <div class="row">
        <div class="col-lg-2">

</div>
	{% if utilisateur and utilisateur.isVerified == false %}
		<div class="alert alert-warning alert-dismissible" role="alert">
			<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
			<div class="alert-message">
				<strong>Votre compte n'est pas activé</strong>,
				<a href="{{ path('resend_verif') }}">renvoyer le lien d'activation</a>
			</div>
		</div>
	{% endif %}
	{% include "_partials/_flash.html.twig" %}
	<div class="container-fluid">
		<div class="row">
			<main class="col-md  px-md-4">
				<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
					<h1 class="h2">Bienvenue {{utilisateur.prenomUtilisateur}}
					</h1>
					<a class="nav-link " href="{{path('app_dashboard_ajouter')}}">
						<span data-feather="file" class="align-text-bottom"></span>
						Ajouter une annonce
					</a>
					<a class="nav-link active mx-2" aria-current="page" href="{{path('app_dashboard')}}">
						<span data-feather="home" class="align-text-bottom"></span>
						Mes annonces
					</a>
				</div>
			</main>
		</div>
	</div>

	<div class="row mx-1">
		{% for animal in animals %}

			<div class="col-lg-4 mb-2" >
				<div class="card shadow-sm " >
					<div class="card-header text-center">
						{{ animal[0].nomAnimal }}<br>
					</div>

						{% if 'http' in animal.image %}
							<img src="{{animal.image}}" class=" card-img-top" >
						{% else %}
							<img src="uploads/{{animal.image}}" class=" card-img-top"  >
						{% endif %}


					<div class="card-body">
						<p class="card-text">
							{{animal[0].texteAnimal | slice(0, 50) | raw }}...</p>
						Age de l'animal:
						{{animal[0].ageAnimal}}
						ans
						<div class="d-flex justify-content-between align-items-center">
							<div class="btn-group">
								<a href="annonce/{{animal[0].IdAnimal}}" type="button" class="btn btn-sm btn-outline-secondary">En savoir plus...</a>
								<a href="dashboard/delete/{{animal[0].IdAnimal}}" type="button" class="btn btn-warning">Supprimer</a>
							</div>
							<small class="text-muted">{{animal[0].prixAnimal}}
								euros</small>
						</div>
					</div>
				</div>
			</div>
		{% endfor %}

		<div class="container ">
			<div class="row mx-auto">
				<div class="col-lg-2 mx-auto">
				<div class="col-lg-4 mx-auto">
					<a type="submit" class="btn btn-dark" href='/deconnexion'>Déconnexion</a>
				</div>
			</div>
		</div>
	</div>
	{% include 'commun/footer.html.twig' %}

{% endblock %}
{% block javascripts %}
{% endblock %}